# Generated by Django 6.0.5 on 2026-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advance', 'Advance'), ('expert', 'Expert')], default='medium', max_length=10),
        ),
    ]
