# Generated by Django 6.0.5 on 2026-05-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0003_usedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('fitb', 'Fill in the Blanks'), ('tf', 'True / False'), ('vsq', 'Very Short Questions'), ('sq', 'Short Questions'), ('lq', 'Long Questions')], max_length=10)),
                ('input_type', models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('youtube', 'YouTube')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('advance', 'Advance'), ('expert', 'Expert')], default='advance', max_length=10)),
                ('language', models.CharField(default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq_app.questionset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
