# Generated by Django 6.0.5 on 2026-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0004_questionset_generatedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='wrong_option',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
