# Generated by Django 6.0.5 on 2026-05-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0005_generatedquestion_wrong_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_grade', models.CharField(blank=True, max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('total_marks', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=10)),
                ('language', models.CharField(default='auto', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('mcq', 'MCQ'), ('fitb', 'Fill in Blanks'), ('tf', 'True / False'), ('vsq', 'Very Short'), ('sq', 'Short Questions'), ('lq', 'Long Questions')], max_length=10)),
                ('question_count', models.IntegerField(default=5)),
                ('marks_each', models.FloatField(default=2)),
                ('order', models.IntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mcq_app.exampaper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(blank=True, max_length=1)),
                ('wrong_option', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcq_app.examsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
