# Generated by Django 6.0.5 on 2026-05-31 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0006_exampaper_examsection_examquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsection',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='section',
        ),
        migrations.DeleteModel(
            name='ExamPaper',
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='ExamSection',
        ),
    ]
