# Generated by Django 6.0.5 on 2026-06-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0007_remove_examsection_paper_remove_examquestion_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('exam_date', models.DateField()),
                ('daily_hours', models.IntegerField(default=4)),
                ('exam_format', models.CharField(default='mixed', max_length=50)),
                ('target_score', models.CharField(default='good', max_length=50)),
                ('rest_days', models.IntegerField(default=1)),
                ('total_marks', models.IntegerField(default=100)),
                ('plan_title', models.CharField(blank=True, max_length=300)),
                ('total_days', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('strategy_note', models.TextField(blank=True)),
                ('revision_tips', models.JSONField(default=list)),
                ('important_topics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date_label', models.CharField(max_length=20)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('daily_goal', models.CharField(blank=True, max_length=500)),
                ('total_hours', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='mcq_app.studyplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('duration', models.IntegerField(default=60)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mcq_app.studyday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('focus_area', models.CharField(max_length=300)),
                ('total_hours', models.FloatField(default=0)),
                ('key_milestone', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='mcq_app.studyplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
