# Generated by Django 6.0.5 on 2026-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0008_studyplan_studyday_studytopic_studyweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login_at', models.DateTimeField(blank=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
    ]
