# Generated by Django 6.0.5 on 2026-06-19 05:25

import django.core.validators
import django.db.models.deletion
import mcq_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0009_userloginlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedquestion',
            options={'ordering': ['order'], 'verbose_name': 'Generated Question', 'verbose_name_plural': 'Generated Questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question Set', 'verbose_name_plural': 'Question Sets'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.AlterModelOptions(
            name='studyday',
            options={'ordering': ['order'], 'verbose_name': 'Study Day', 'verbose_name_plural': 'Study Days'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study Plan', 'verbose_name_plural': 'Study Plans'},
        ),
        migrations.AlterModelOptions(
            name='studytopic',
            options={'ordering': ['order'], 'verbose_name': 'Study Topic', 'verbose_name_plural': 'Study Topics'},
        ),
        migrations.AlterModelOptions(
            name='studyweek',
            options={'ordering': ['order'], 'verbose_name': 'Study Week', 'verbose_name_plural': 'Study Weeks'},
        ),
        migrations.AlterModelOptions(
            name='usedquestion',
            options={'verbose_name': 'Used Question', 'verbose_name_plural': 'Used Questions'},
        ),
        migrations.AlterModelOptions(
            name='userloginlog',
            options={'ordering': ['-login_at'], 'verbose_name': 'User Login Log', 'verbose_name_plural': 'User Login Logs'},
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='question_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='wrong_option',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Wrong Option (T/F only)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1, validators=[mcq_app.models.validate_correct_answer], verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=500, verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=500, verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=500, verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=500, verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advance', 'Advance'), ('expert', 'Expert')], default='advance', max_length=10, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='input_type',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('youtube', 'YouTube')], max_length=20, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='language',
            field=models.CharField(default='auto', max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='question_type',
            field=models.CharField(choices=[('fitb', 'Fill in the Blanks'), ('tf', 'True / False'), ('vsq', 'Very Short Questions'), ('sq', 'Short Questions'), ('lq', 'Long Questions')], max_length=10, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advance', 'Advance'), ('expert', 'Expert')], default='advance', max_length=10, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='input_type',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('youtube', 'YouTube')], max_length=20, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='auto', max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mcq_app.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Questions'),
        ),
        migrations.AlterField(
            model_name='studyday',
            name='daily_goal',
            field=models.CharField(blank=True, max_length=500, verbose_name='Daily Goal'),
        ),
        migrations.AlterField(
            model_name='studyday',
            name='date_label',
            field=models.CharField(max_length=20, verbose_name='Date Label'),
        ),
        migrations.AlterField(
            model_name='studyday',
            name='day_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Day Number'),
        ),
        migrations.AlterField(
            model_name='studyday',
            name='is_rest_day',
            field=models.BooleanField(default=False, verbose_name='Rest Day?'),
        ),
        migrations.AlterField(
            model_name='studyday',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studyday',
            name='total_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Hours'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='daily_hours',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Daily Study Hours'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='exam_date',
            field=models.DateField(verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='exam_format',
            field=models.CharField(default='mixed', max_length=50, verbose_name='Exam Format'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='rest_days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Rest Days Per Week'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='subject_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='target_score',
            field=models.CharField(default='good', max_length=50, verbose_name='Target Score'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='total_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='total_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='total_marks',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Marks'),
        ),
        migrations.AlterField(
            model_name='studytopic',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='studytopic',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advance', 'Advance'), ('expert', 'Expert')], default='advance', max_length=20, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='studytopic',
            name='duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='studytopic',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studytopic',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='studytopic',
            name='topic',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='studyweek',
            name='focus_area',
            field=models.CharField(max_length=300, verbose_name='Focus Area'),
        ),
        migrations.AlterField(
            model_name='studyweek',
            name='key_milestone',
            field=models.CharField(max_length=500, verbose_name='Key Milestone'),
        ),
        migrations.AlterField(
            model_name='studyweek',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studyweek',
            name='total_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Hours'),
        ),
        migrations.AlterField(
            model_name='studyweek',
            name='week_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Week Number'),
        ),
        migrations.AlterField(
            model_name='usedquestion',
            name='question_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='usedquestion',
            name='topic_hash',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.MinLengthValidator(32)], verbose_name='Topic Hash (MD5)'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True = abhi logged in hai', verbose_name='Currently Active?'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Login Time'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logout Time'),
        ),
        migrations.AlterUniqueTogether(
            name='usedquestion',
            unique_together={('question_text', 'topic_hash')},
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['email', '-login_at'], name='mcq_app_use_email_bb2c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('total_questions'))), name='score_lte_total_questions'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='score_gte_zero'),
        ),
    ]
