# Generated by Django 6.0.5 on 2026-08-15 11:51

import mcq_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0010_alter_generatedquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='exam_date',
            field=models.DateField(validators=[mcq_app.models.validate_future_date], verbose_name='Exam Date'),
        ),
    ]
