# Generated by Django 6.0.5 on 2026-09-02 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0012_questionset_user_quiz_user_studyplan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True = currently logged in', verbose_name='Currently Active?'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (.docx)'), ('image', 'Image'), ('youtube', 'YouTube URL'), ('text', 'Raw Text')], max_length=20, verbose_name='File Type')),
                ('file_size_bytes', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('generation_type', models.CharField(choices=[('quiz', 'MCQ Quiz'), ('question', 'Question Set'), ('plan', 'Study Plan')], max_length=20, verbose_name='Generation Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question_set', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file', to='mcq_app.questionset', verbose_name='Generated Questions')),
                ('quiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file', to='mcq_app.quiz', verbose_name='Generated Quiz')),
                ('study_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file', to='mcq_app.studyplan', verbose_name='Generated Plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
