# Generated by Django 6.0.5 on 2026-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0013_alter_userloginlog_is_active_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytopic',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20, verbose_name='Difficulty'),
        ),
    ]
