# Generated by Django 6.0.5 on 2026-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0014_alter_studytopic_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='language',
            field=models.CharField(default='english', max_length=20, verbose_name='Language'),
        ),
    ]
